language: python

python:
    - "2.7"

install:
    - "pip install -q -r requirements/dev.txt ."

before_script:
  - "pep8 lims"
  - "pyflakes lims"

script:
    - coverage run --source lims setup.py test

after_success:
    coveralls

notifications:
    email: false
